# Generated by Django 2.2 on 2019-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='dest_stn',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='train',
            name='source_stn',
            field=models.TextField(default=True),
        ),
    ]
