# Generated by Django 2.2 on 2019-04-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190412_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
