# Generated by Django 2.2 on 2019-04-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_train_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
