# Generated by Django 2.2 on 2019-04-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
