# Generated by Django 2.2 on 2019-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('reserved', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nta', models.IntegerField()),
                ('ntc', models.IntegerField()),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('source_stn', models.TextField(default=True)),
                ('dest_stn', models.TextField(default=True)),
                ('doj', models.DateTimeField()),
                ('totalfare', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='train',
            name='price',
            field=models.IntegerField(),
        ),
    ]
