# Generated by Django 2.2 on 2019-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190417_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='aadhaarno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='contactno',
            field=models.IntegerField(default=0),
        ),
    ]
